# .cargo/audit.toml

[advisories]
# explicitly silence the Linux GTK3 stack + the GLib iterator issue
# later on, when dioxus moves to GTK4, we'll release for linux
ignore = [
  "RUSTSEC-2024-0411", # gdkwayland-sys
  "RUSTSEC-2024-0412", # gdk
  "RUSTSEC-2024-0413", # atk
  "RUSTSEC-2024-0414", # gdkx11-sys
  "RUSTSEC-2024-0415", # gtk
  "RUSTSEC-2024-0416", # atk-sys
  "RUSTSEC-2024-0417", # gdkx11
  "RUSTSEC-2024-0418", # gdk-sys
  "RUSTSEC-2024-0419", # gtk3-macros
  "RUSTSEC-2024-0420", # gtk-sys
  "RUSTSEC-2024-0429", # glib VariantStrIter unsoundness
]

# Control which “informational” categories are printed.
# Use [] to hide them entirely, or e.g. ["yanked"] to only show yanked.
informational_warnings = []
# alternatives:
# informational_warnings = ["yanked"]
# informational_warnings = ["unmaintained","yanked","notice"]  # default-ish

[target]
# Limit advisories to your shipping platforms
os   = ["macos", "windows"]
arch = ["aarch64", "x86_64"]

[output]
quiet = true
show_tree = false
